# region Docker Variables

docker_network: "app-internal-nw"
docker_network_type: "bridge"

test_image: "alpine"
test_command: "sleep 30d"
test_container_name: "docker-alpine-test"

# endregion

# region Warmup Variables

system_packages:
  - curl
  - nginx
  - nftables
  - virtualenv
  - python3-pip
  - python3-venv
  - ca-certificates
  - python3-setuptools
  - apt-transport-https
  - software-properties-common

# endregion

# region Security Variables

cron_script_dir: "/etc/cron.d"

# endregion

# region NGINX Variables

server_name: "*.hack-nocturne.in"

# Cloudflare Origin Cert & Key paths
ssl_cert_path: /etc/nginx/ssl/cf_origin.pem
ssl_key_path:  /etc/nginx/ssl/cf_origin.key

# Health-checks (must return 200)
healthcheck_path: /health-check
healthcheck_host_header: hack-nocturne.in
health_timeout_seconds: 2
health_retries: 3

# Blue pool
blue_upstreams:
  - { host: "127.0.0.1", port: 2020 }
  - { host: "127.0.0.1", port: 2021 }

# Green pool
green_upstreams:
  - { host: "127.0.0.1", port: 4040 }
  - { host: "127.0.0.1", port: 4041 }

# endregion
