---
- hosts: all
  become: true

  vars:
    test_image: "alpine"
    test_command: "sleep 30d"
    test_container_name: "docker-alpine-test"

  tasks:
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/debian bookworm stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Install Docker Module for Python
      apt:
        name:
          - python3-docker
        state: present
        update_cache: yes

    - name: Create docker group
      group:
        name: docker
        state: present

    - name: Add current user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
      when: ansible_user is defined

    - name: Create dedicated Docker network
      community.docker.docker_network:
        name: "{{ docker_network }}"
        driver: "{{ docker_network_type }}"
        internal: false

    - name: Start and enable Docker service
      systemd:
        name: docker
        state: started
        enabled: yes
        daemon_reload: yes

    - name: Configure Docker to start on boot
      systemd:
        name: docker
        enabled: yes

    - name: Pull alpine Docker image
      community.docker.docker_image:
        name: "{{ test_image }}"
        source: pull

    - name: Create alpine container
      community.docker.docker_container:
        image: "{{ test_image }}"
        name: "{{ test_container_name }}"
        command: "{{ test_command }}"
        state: started
